name: win_toast_example
description: Demonstrates how to use the win_toast plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  win_toast:
    path: ../
  cupertino_icons: ^1.0.2
  xml: ^5.1.2
  mixin_logger: ^0.0.2
  path_provider: ^2.0.11
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  msix: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.png

msix_config:
  display_name: WinToastExample
  identity_name: com.example.coba
  build_windows: true
  debug: false
  logo_path: assets/image.png
  toast_activator:
    clsid: 936C39FC-6BBC-4A57-B8F8-7C627E401B2F
    display_name: "WinToastExample"
  msix_version: 1.0.4.0