name: win_toast
description: a flutter plugin that allows users to create and display toast notifications to notification center on the Windows operating system.
version: 0.3.0
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/win_toast

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WinToastPlugin
